databases:
  - name: postgres
    ipAllowList: []
    databaseName: fleetXpert_backend
    user: tabz

services:
  - type: web
    name: FleetXpert_Backend
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false